### ISSUE TITLE
UI Confirm Course Info Slide

### ISSUE THREAD

**Issue by melj** [prime7/codehub_calendar#18]
**WHAT**
- The 3rd page of the carousel will show the user the courses they've have uploaded syllabuses for along with their relevant dates.
-  From this slide, user's should have the option to edit the information. When the user hit's edit, it will get input from the user to save the changes or cancel them.

**DESIGN NOTES**
Please refer to Dongheon's designs on the general layout and idea.
- The layout should be minimal, displaying just enough information to the user without overwhelming them. SO, only display the course names, some details and an option to expand the details for that course, where the relevant dates will be shown. Please refer to Bootstrap's collapse component.
- There should be button beside each editable item, an intuitive icon should be used

**Comment by denngall** [comment]
There can be 2 midterms and several number of assignments -> how to store them in our object?

**Comment by melj** [comment]
You can use an array to store the two midterm dates
