### ISSUE TITLE
Website UI Design

### ISSUE THREAD

**Issue by VanillaTaco** [prime7/codehub_calendar#3]
Format early draft of HTML/CSS based on UI Design

**Comment by melj** [comment]
**Meeting notes**
Make sure the app lives in a single page, so we can save the data between each of the steps.
Bootstrap carousel for the individual steps between the pdf conversion
Bootstrap modal for the course details and editing page
Douglas Background image for the website, with carousel centred, a header and a footer
Lets add our social media links in the footer too

**Comment by melj** [comment]
commit# fbba0bfdee8b280f2876499385fedf28bb1fe890
