### ISSUE TITLE
PDF Converting to Text

### ISSUE THREAD

**Issue by GeekedAt-Birth** [prime7/codehub_calendar#5]
**TASKS TO DO**
#10 This will be your task 1
#8  This will be your task 2

**Comment by GeekedAt-Birth** [comment]
Most research pointed to the use PDF.js library

**PDF.js** (JS library that helps us render a pdf file in the in an html canvas element) (I still don’t understand how it's doing it)  
--PDF.js was mainly designed to read and render PDF's. However it be manipulated for text extraction and search and these features rely on the underlying text parsing and extraction engine, which defines the text overlay.
--PDFParser & PDFReader (Node.js) (alternatives)
--Pdftabextract (python library) (last resort)

--We also decided to consider the use of Python libraries.

**CONCLUSION**
@agam23  found that the use tabular.py  python library would be easier.

**Comment by melj** [comment]
conclusion was found with Tabula.py
