### ISSUE TITLE
Extract text from the pdf  

### ISSUE THREAD

**Issue by GeekedAt-Birth** [prime7/codehub_calendar#8]
** HOW**
Now that you have a library try it out

**Comment by melj** [comment]
We will be using a python library to implement the extraction of text from PDF.
For this we will need a server, and python script to convert files passed from the front end.
Tabula.py is the top contender so far.
@GeekedAt-Birth @agam23

**Comment by GeekedAt-Birth** [comment]
**NEW TASK**
- Research how to structure a full stack webapp with python. / how to setup a server that can access a python script (node.js)
- Understand (Tabular.py) and how to link it to the web.

**Comment by melj** [comment]
tabula.py
